# Generated by Django 2.1 on 2018-08-27 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('fav', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=False)),
                ('startField', models.TimeField()),
                ('endField', models.TimeField()),
            ],
        ),
    ]
